name: dartx
description: Superpowers for Dart. Collection of useful static extension methods.
version: 0.4.1
homepage: https://github.com/leisim/dartx

environment:
  sdk: ">=2.6.0-dev.5.0 <3.0.0"

dependencies:
  collection:
  path: ^1.6.0
  crypto: ">=2.1.0 <2.2.0"
  characters:
  time: ^1.2.0

dev_dependencies:
  test: ^1.9.2
  pedantic: ^1.8.0
